--[[
	id: LMgSNcBjHFednYuJXhlZA
	name: For Timka
	description: just for timka
	time1: 2021-05-10 16:28:39.821705+00
	time2: 2021-05-10 16:28:39.821706+00
	uploader: 138
	uploadersession: jXNavnWRna4LC26tapUlI--RvzT85-
	flag: f
--]]

-------------------- BLACKLIST --------------------
Players = game.Players
for i,v in pairs(Players:GetDescendants()) do
	if v.Name == "Guest537561" and v.Character == "Guest537561" and v.CharacterAppearance == "602725431" then
		v:Kick("You're not whitelsited, skiddie :)) ")
	end
end
-------------------- END OF BLACKLIST --------------------





-------------------- ARGS --------------------
local bb=game:service'VirtualUser'

local leave = {
	[1] = "Elevators",
	[2] = "Leave"
}

-- Script generated by SimpleSpy - credits to exx#9394
-- Script generated by SimpleSpy - credits to exx#9394

local car1 = {
    [1] = "Troops",
    [2] = "Place",
    [3] = "Military Base",
    [4] = {
        ["Rotation"] = CFrame.new(Vector3.new(0, 0, 0), Vector3.new(-0, -0, -1)),
        ["Position"] = Vector3.new(23.352367401123, 0.24409055709839, -39.874458312988)
    }
}

--game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(args))

-- Script generated by SimpleSpy - credits to exx#9394

local car2 = {
    [1] = "Troops",
    [2] = "Place",
    [3] = "Military Base",
    [4] = {
        ["Rotation"] = CFrame.new(Vector3.new(0, 0, 0), Vector3.new(-0, -0, -1)),
        ["Position"] = Vector3.new(19.738430023193, 0.24408578872681, -40.385467529297)
    }
}

--game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(args))

-- Script generated by SimpleSpy - credits to exx#9394

local car3 = {
    [1] = "Troops",
    [2] = "Place",
    [3] = "Military Base",
    [4] = {
        ["Rotation"] = CFrame.new(Vector3.new(0, 0, 0), Vector3.new(-0, -0, -1)),
        ["Position"] = Vector3.new(15.582523345947, 0.24405097961426, -40.660121917725)
    }
}

--game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(args))


-- Script generated by SimpleSpy - credits to exx#9394

local car4 = {
    [1] = "Troops",
    [2] = "Place",
    [3] = "Military Base",
    [4] = {
        ["Rotation"] = CFrame.new(Vector3.new(0, 0, 0), Vector3.new(-0, -0, -1)),
        ["Position"] = Vector3.new(33.164100646973, 0.24414777755737, -39.85982131958)
    }
}

--game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(args))



local avi = {
    [1] = "Troops",
    [2] = "Place",
    [3] = "Ace Pilot",
    [4] = {
        ["Rotation"] = CFrame.new(Vector3.new(0, 0, 0), Vector3.new(-0, -0, -1)),
        ["Position"] = Vector3.new(8.7175188064575, 0.75140243768692, -5.2340936660767)
    }
}


--game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(args))

-- Script generated by SimpleSpy - credits to exx#9394

local avia = {
     [1] = "Troops",
    [2] = "Place",
    [3] = "Ace Pilot",
    [4] = {
        ["Rotation"] = CFrame.new(Vector3.new(0, 0, 0), Vector3.new(-0, -0, -1)),
        ["Position"] = Vector3.new(12.821451187134, 0.46414053440094, -7.1834239959717)
    }
}

--game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(args))

-- Script generated by SimpleSpy - credits to exx#9394

local car = {
    [1] = "Troops",
    [2] = "Place",
    [3] = "Military Base",
    [4] = {
        ["Rotation"] = CFrame.new(Vector3.new(0, 0, 0), Vector3.new(-0, -0, -1)),
        ["Position"] = Vector3.new(28.455593109131, 0.24414730072021, -39.732810974121)
    }
}

--game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(args))


-- Script generated by SimpleSpy - credits to exx#9394

local rocket = {
    [1] = "Troops",
    [2] = "Place",
    [3] = "Rocketeer",
    [4] = {
        ["Rotation"] = CFrame.new(Vector3.new(0, 0, 0), Vector3.new(-0, -0, -1)),
        ["Position"] = Vector3.new(9.8406744003296, 0.83964437246323, -8.4655704498291)
    }
}

--game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(args))


-- Script generated by SimpleSpy - credits to exx#9394

local toxic = {
    [1] = "Troops",
    [2] = "Place",
    [3] = "Toxic Gunner",
    [4] = {
        ["Rotation"] = CFrame.new(Vector3.new(0, 0, 0), Vector3.new(-0, -0, -1)),
        ["Position"] = Vector3.new(13.208227157593, 0.3734884262085, -12.000759124756)
    }
}

--game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(args))

local toxic2 = {
    [1] = "Troops",
    [2] = "Place",
    [3] = "Toxic Gunner",
    [4] = {
        ["Rotation"] = CFrame.new(Vector3.new(0, 0, 0), Vector3.new(-0, -0, -1)),
        ["Position"] = Vector3.new(-13.942234039307, 0.24512767791748, -52.656116485596)
    }
}


-- Script generated by SimpleSpy - credits to exx#9394

local toxic1 = {
    [1] = "Troops",
    [2] = "Place",
    [3] = "Toxic Gunner",
    [4] = {
        ["Rotation"] = CFrame.new(Vector3.new(0, 0, 0), Vector3.new(-0, -0, -1)),
        ["Position"] = Vector3.new(13.05858707428, 0.47033816576004, -10.057467460632)
    }
}

--game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(args))

local toxic3 = {
    [1] = "Troops",
    [2] = "Place",
    [3] = "Toxic Gunner",
    [4] = {
        ["Rotation"] = CFrame.new(Vector3.new(0, 0, 0), Vector3.new(-0, -0, -1)),
        ["Position"] = Vector3.new(10.853956222534, 0.58710277080536, -11.772247314453)
    }
}



local sled = {
    [1] = "Troops",
    [2] = "Place",
    [3] = "Sledger",
    [4] = {
        ["Rotation"] = CFrame.new(Vector3.new(0, 0, 0), Vector3.new(-0, -0, -1)),
        ["Position"] = Vector3.new(-16.911598205566, 0.24511432647705, -52.161106109619)
    }
}



local sled1 = {
    [1] = "Troops",
    [2] = "Place",
    [3] = "Sledger",
    [4] = {
        ["Rotation"] = CFrame.new(Vector3.new(0, 0, 0), Vector3.new(-0, -0, -1)),
        ["Position"] = Vector3.new(1.3333945274353, 0.24412822723389, -59.545124053955)
    }
}
-- Script generated by SimpleSpy - credits to exx#9394

local skip = {
    [1] = "Waves",
    [2] = "Skip"
}

--game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(args))



-------------------- END OF ARGS --------------------




-------------------- JOINING HARDCORE LOBBY --------------------
repeat wait() until game:IsLoaded()

if game.PlaceId == 3260590327 then
    workspace.Elevators.Elevator.Name = "re"
   workspace.Elevators.Elevator.Name = "re"
   workspace.Elevators.Elevator.Name = "re"
   workspace.Elevators.Elevator.Name = "re"
   workspace.Elevators.Elevator.Name = "re"
   workspace.Elevators.Elevator.Name = "re"
   workspace.Elevators.Elevator.Name = "re"
   workspace.Elevators.Elevator.Name = "re"
   workspace.Elevators.Elevator.Name = "re"
   workspace.Elevators.Elevator.Name = "re"
   workspace.Elevators.Elevator.Name = "re"
   workspace.Elevators.Elevator.Name = "Elevatorr"
   workspace.Elevators.Elevator.Name = "Elevator"
	print("im not dead yet")
	wait(8)
	while wait() do
		for i,v in pairs(workspace.Elevators.Elevator:GetDescendants()) do
			if v.Name == "Players" and v:IsA("IntValue") and v.Value == 0 and v.Parent.Map.Title.Value =="Wrecked Battlefield" then
				if v.Parent.Parent.name ~= "Event" then
					print("jonining elevator")
					wait()
					game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = v.Parent.Parent.Touch.CFrame 
				   end
				end
			end
			
			for i,v in pairs(workspace.Elevators.Elevatorr:GetDescendants()) do
			if v.Name == "Players" and v:IsA("IntValue") and v.Value == 0 and v.Parent.Map.Title.Value =="Wrecked Battlefield" then
				if v.Parent.Parent.name ~= "Event" then
					print("jonining elevator")
					wait()
					game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = v.Parent.Parent.Touch.CFrame 
				   end
				end
			end
		end
    end
-------------------- END OF HARDCORE LOBBY JOIN --------------------




-------------------- START OF GAME SHITTTTT --------------------
repeat wait() until game:IsLoaded()
print("huh")
if game.PlaceId == 5591597781 then
    print("huhhhh")
	game:service'Players'.LocalPlayer.Idled:connect(function()
		bb:CaptureController()bb:ClickButton2(Vector2.new())
	end)
if #game.Players:children()>1 then game:GetService("TeleportService"):Teleport(3260590327, game.Players.LocalPlayer)
end
print("huhhhhhhhh")
-------------------- FUNCTIONS --------------------
-- ( big thanks goes to  Subaru112, he's made them  )

--:sub(4)
--game.Players.LocalPlayer.PlayerGui.GameGui.Health.Wave.Text == "WAVE 0"
--game.Players.LocalPlayer.PlayerGui.GameGui.Health.Time == "00:05"

local wave = game.Players.LocalPlayer.PlayerGui.GameGui.Health.Wave
local timer = game.Players.LocalPlayer.PlayerGui.GameGui.Health.Time
local cash = game.Players.LocalPlayer.Cash

local towerers = {}

workspace.Towers.ChildAdded:Connect(function(tower)
table.insert(towerers,tower)
end)


function WaitUntilWave(wavee)
repeat
wait()
until tonumber(wave.Text:sub(6)) >= wavee
end

function WaitUntilTime(tim)
repeat
wait()
until tonumber(timer.Text:sub(4)) <= tim
end

function WaitUntilTimeAtWave(wavee,tim)
repeat
wait()
until tonumber(timer.Text:sub(4)) <= tim and tonumber(wave.Text:sub(6)) >= wavee
end

function WaitUntilCash(cashh)
repeat
wait()
until cash.Value >= cashh
end

function WaitUntilWaveAndCash(wavee,cashh)
repeat
wait()
until tonumber(wave.Text:sub(6)) >= wavee and cash.Value >= cashh
end

function WaitUntilTimeAndCash(tim,cashh)
repeat
wait()
until tonumber(timer.Text:sub(4)) <= tim and cash.Value >= cashh
end

function WaitUntilTimeAtWaveAndCash(wavee,tim,cashh)
repeat
wait()
until tonumber(timer.Text:sub(4)) <= tim and tonumber(wave.Text:sub(6)) >= wavee and cash.Value >= cashh
end


function Upgrade(troopPos)
local up = {
[1] = "Troops",
[2] = "Upgrade",
[3] = "Set",
[4] = {
["Troop"] = towerers[troopPos]
}
}
game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(up))
end

function Sell(troopPos)
    local sell = {
    [1] = "Troops",
    [2] = "Sell",
    [3] = {
        ["Troop"] = towerers[troopPos]
    }
}

game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(sell))
end

function Place(troop)
game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(troop))
end

function skip()
game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(skip))
end

-------------------- END OF FUNCTIONS
WaitUntilCash(750)
print("cash?")
Place(avi)
WaitUntilCash(375)
Upgrade(1)
WaitUntilCash(525)
Upgrade(1)

WaitUntilCash(750)
print("what")
Place(avia)
print("you sure?")
WaitUntilCash(375)
Upgrade(2)
WaitUntilCash(525)
Upgrade(2)
WaitUntilCash(800)
Place(car)
WaitUntilCash(300)
Upgrade(3)
WaitUntilCash(600)
Upgrade(3)
WaitUntilCash(600)
Place(car1)
WaitUntilCash(300)
Upgrade(4)
WaitUntilCash(600)
Upgrade(4)
WaitUntilCash(600)
Place(car2)
WaitUntilCash(300)
Upgrade(5)
WaitUntilCash(600)
Upgrade(5)
WaitUntilCash(600)
Place(car3)
WaitUntilCash(300)
Upgrade(6)
WaitUntilCash(600)
Upgrade(6)
WaitUntilCash(600)
Place(car4)
WaitUntilCash(300)
Upgrade(7)
WaitUntilCash(600)
Upgrade(7)
WaitUntilCash(1275)
Place(rocket)
WaitUntilCash(525)
Upgrade(8)
WaitUntilCash(600)
Place(toxic)
WaitUntilCash(225)
Upgrade(9)
WaitUntilCash(600)
Upgrade(9)
WaitUntilCash(600)
Place(toxic1)
WaitUntilCash(225)
Upgrade(10)
WaitUntilCash(600)
Upgrade(10)
WaitUntilCash(525)
Place(sled)
WaitUntilCash(375)
Upgrade(11)
WaitUntilCash(750)
Upgrade(11)
WaitUntilCash(2250)
Upgrade(11)
Place(toxic2)
WaitUntilCash(225)
Upgrade(12)
WaitUntilCash(600)
Upgrade(12)
WaitUntilCash(600)
Place(toxic3)
WaitUntilCash(225)
Upgrade(13)
WaitUntilCash(600)
Upgrade(13)
WaitUntilCash(525)
Place(sled1)
WaitUntilCash(375)
Upgrade(14)
WaitUntilCash(750)
Upgrade(14)
Place(toxic3)
WaitUntilCash(225)
Upgrade(15)
WaitUntilCash(600)
Upgrade(15)
while wait() do 
    if game.Players.LocalPlayer.PlayerGui.GameGui.Health.Survival.Count.Text == "0/100" then
        wait(10)
        game:GetService("TeleportService"):Teleport(3260590327, game.Players.LocalPlayer)
        end
    end
end
